## Replace all occurrences of pixie.example.com with the custom domain name you wish to use
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-ingress-grpcs
  namespace: plc
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - pixie.example.com
    - work.pixie.example.com
    secretName: cloud-proxy-tls-certs
  rules:
  - host: pixie.example.com
    http:
      paths:
      - path: /pl.cloudapi.ArtifactTracker/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.services.VZConnService/
        pathType: Prefix
        backend:
          service:
            name: vzconn-service
            port:
              number: 51600
      - path: /px.cloudapi.ArtifactTracker/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.APIKeyManager/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.AuthService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.ConfigService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.OrganizationService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.PluginService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.UserService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.VizierClusterInfo/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.VizierDeploymentKeyManager/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.VizierImageAuthorization/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.api.vizierpb.VizierService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 4444
  - host: work.pixie.example.com
    http:
      paths:
      - path: /pl.cloudapi.ArtifactTracker/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.services.VZConnService/
        pathType: Prefix
        backend:
          service:
            name: vzconn-service
            port:
              number: 51600
      - path: /px.cloudapi.ArtifactTracker/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.APIKeyManager/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.AuthService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.ConfigService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.OrganizationService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.PluginService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.UserService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.VizierClusterInfo/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.VizierDeploymentKeyManager/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.cloudapi.VizierImageAuthorization/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 5555
      - path: /px.api.vizierpb.VizierService/
        pathType: Prefix
        backend:
          service:
            name: cloud-proxy-service
            port:
              number: 4444
